name: aymurai-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.2.1
  - openjdk==22.0.1
  - git==2.46.2
  - pip:
    - ./aymurai-1.1.0-py3-none-any.whl
    # Instal forked version of textract to fix this issue
    # https://github.com/deanmalmgren/textract/issues/313
    -  textract @ git+https://github.com/MaxEtMoritz/textract@master
